bug-fix: breaks on non ascii characters.
saw an error:
body = str(body) + "\n" + self.__canonical(str(url))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in
position 36: ordinal not in range(128)